import { Header } from "@/components/Header";
import clsx from "clsx";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={clsx(
          "text-large min-h-full bg-white-97 font-normal leading-normal text-grey-15",
          beVietnamPro.className,
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
